# -*- coding: utf-8 -*-
"""basic python programs

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aB8v2Y9G5imqYy3Pxg2H49_G-QaWjBop
"""

print('lam divya sree')

print("lam divya sree")
1+9+0+9+2+0+0+5

1+9+0+9+2+0+0+5

6*9

568/748

x=18
y='divya'
print(x)
print(y)

x=str(45)
y=int(3)
z=float(3.897)
print(x)
print(y)
print(z)

x=18
y='divya'
z=2.0
print(type(x))
print(type(y))
print(type(z))

x="divya"
print(x)
x=2
print(x)

a=4
A="divya"

myvar="divya"
MyVar="divya"
my_var="divya"
myvar2="divya"
MYVar="divya"
_my_var="divya"

x,y,z="orange","banana","cherry"
print(x)
print(y)
print(z)

x=_y=z="orange"
_x=y=z2="orange"
x=y=z="orange"
x2=y3=z4="orange"
_x=_y=_z="orange"
print(x)
print(y)
print(z)

fruits=["apple","banana","cherry"]
x,y,z=fruits
print(x)
print(y)
print(z)
print(fruits)

fruits={"apple","banana","cherry"}
x,y,z=fruits
print(fruits)

fruits=("apple","banana","cherry")
x,y,z=fruits
print(fruits)

fruits=["apple","banana","cherry"]
x,y,z=fruits
print(x)
print(y)
print(z)

thisdict={
    "brand":"ford"
    "model":"mustang"
    "year":1964
}

x="python"
y="is"
z="awesome"
print(x+y+z)

import sys
import sys as divya
print(sys.version)
print(divya.version)

if 5>2:
  print()